### ISSUE TITLE
输入问题报错

### ISSUE THREAD

**Issue by zhongsb** [liuhuanyong/QASystemOnMedicalKG#25]
model init finished ......
用户:头疼怎么办
小勇: 您好，我是小勇医药智能助理，希望可以帮到您。如果没答上来，可联系https://liuhuanyong.github.io/。祝您身体棒棒！
用户:头痛怎么办
`Traceback (most recent call last):
  File "D:\program\Anaconda\envs\py36\lib\site-packages\py2neo\database.py", line 828, in run
    entities=entities))
  File "D:\program\Anaconda\envs\py36\lib\site-packages\py2neo\internal\connectors.py", line 292, in run
    return self._run_1(statement, parameters, graph, keys, entities)
  File "D:\program\Anaconda\envs\py36\lib\site-packages\py2neo\internal\connectors.py", line 241, in _run_1
    cx = self.pool.acquire()
  File "D:\program\Anaconda\envs\py36\lib\site-packages\neobolt\direct.py", line 719, in acquire
    return self.acquire_direct(self.address)
  File "D:\program\Anaconda\envs\py36\lib\site-packages\neobolt\direct.py", line 612, in acquire_direct
    connection = self.connector(address, error_handler=self.connection_error_handler)
  File "D:\program\Anaconda\envs\py36\lib\site-packages\py2neo\internal\connectors.py", line 227, in connector
    encrypted=cx_data["secure"], **kwargs)
  File "D:\program\Anaconda\envs\py36\lib\site-packages\neobolt\direct.py", line 976, in connect
    raise last_error
  File "D:\program\Anaconda\envs\py36\lib\site-packages\neobolt\direct.py", line 968, in connect
    connection = _handshake(s, address, der_encoded_server_certificate, **config)
  File "D:\program\Anaconda\envs\py36\lib\site-packages\neobolt\direct.py", line 936, in _handshake
    connection.hello()
  File "D:\program\Anaconda\envs\py36\lib\site-packages\neobolt\direct.py", line 249, in hello
    self.sync()
  File "D:\program\Anaconda\envs\py36\lib\site-packages\neobolt\direct.py", line 531, in sync
    detail_delta, summary_delta = self.fetch()
  File "D:\program\Anaconda\envs\py36\lib\site-packages\neobolt\direct.py", line 422, in fetch
    return self._fetch()
  File "D:\program\Anaconda\envs\py36\lib\site-packages\neobolt\direct.py", line 464, in _fetch
    response.on_failure(summary_metadata or {})
  File "D:\program\Anaconda\envs\py36\lib\site-packages\neobolt\direct.py", line 778, in on_failure
    raise AuthError(message)
neobolt.exceptions.AuthError: The client is unauthorized due to authentication failure.

During handling of the above exception, another exception occurred:`

**Comment by TahoeWang** [comment]
我跟你报一样的错误，请问解决了吗？

**Comment by ZiteHe** [comment]
我也是输入头痛报错……

**Comment by Hanlard** [comment]
这个是neo4j没登录上去

**Comment by ZJU-lznb** [comment]
neo4j要本地先打开那个小黑窗的吧
neo4j.bat console
