### ISSUE TITLE
python build_medicalgraph.py Error

### ISSUE THREAD

**Issue by WeiYangBin** [liuhuanyong/QASystemOnMedicalKG#33]
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/py2neo/database.py", line 88, in __new__
    inst = cls._instances[key]
KeyError: '099ab23f1c4224abdb8165aafa7dd19a'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build_medicalgraph.py", line 270, in <module>
    handler = MedicalGraph()
  File "build_medicalgraph.py", line 20, in __init__
    password="123456")
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/py2neo/database.py", line 305, in __new__
    database = Database(uri, **settings)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/py2neo/database.py", line 97, in __new__
    user_agent=connection_data["user_agent"])
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/neo4j/v1/api.py", line 133, in __new__
    return subclass(uri, **config)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/neo4j/v1/direct.py", line 73, in __new__
    pool.release(pool.acquire())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/neo4j/v1/direct.py", line 44, in acquire
    return self.acquire_direct(self.address)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/neo4j/bolt/connection.py", line 455, in acquire_direct
    connection.pool = self
AttributeError: 'NoneType' object has no attribute 'pool'
```
您好这种错误是什么原因导致的

**Comment by gaohanga** [comment]
请问解决了么？我也有这个问题

**Comment by Josoope** [comment]
我也遇到这个问题
