### ISSUE TITLE
老师你好，运行数据导入的脚本之后，导进去的只有节点，关系导不进去。您能告诉我一下应该注意哪些地方吗

### ISSUE THREAD

**Issue by xhb951120474** [liuhuanyong/QASystemOnMedicalKG#34]

**Comment by xhb951120474** [comment]
Traceback (most recent call last):
  File "D:/leave/PY/QASystemOnMedicalKG-master/build_medicalgraph.py", line 271, in <module>
    handler.create_graphrels()
  File "D:/leave/PY/QASystemOnMedicalKG-master/build_medicalgraph.py", line 204, in create_graphrels
    self.create_relationship('Disease', 'Food', rels_recommandeat, 'recommand_eat', '推荐食谱')
  File "D:/leave/PY/QASystemOnMedicalKG-master/build_medicalgraph.py", line 228, in create_relationship
    query = "match(p:%s),(q:%s) where p.name='%s'and q.name='%s' create (p)-[rel:%s{name:'%s'}]->(q)" % ( start_node, end_node, p,q, rel_type, rel_name)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)

**Comment by Malestudents** [comment]
UnicodeDecodeError: 'ascii' 字符编码问题 py脚本开始声明一下# coding:utf-8

**Comment by xhb951120474** [comment]
> UnicodeDecodeError：'ascii'字符编码问题py脚本开始声明一下#coding：utf-8

好的，我试一下。谢谢

**Comment by xhb951120474** [comment]
> UnicodeDecodeError: 'ascii' 字符编码问题 py脚本开始声明一下# coding:utf-8

吧脚本都改为UTF-8了，还是不行。只有节点导入，关系导入不成功

**Comment by Malestudents** [comment]
错误信息贴出来啊

**Comment by xhb951120474** [comment]
> 错误信息贴出来啊

File "D:/leave/PY/QASystemOnMedicalKG-master/build_medicalgraph.py", line 271, in
handler.create_graphrels()
File "D:/leave/PY/QASystemOnMedicalKG-master/build_medicalgraph.py", line 204, in create_graphrels
self.create_relationship('Disease', 'Food', rels_recommandeat, 'recommand_eat', '推荐食谱')
File "D:/leave/PY/QASystemOnMedicalKG-master/build_medicalgraph.py", line 228, in create_relationship
query = "match(p:%s),(q:%s) where p.name='%s'and q.name='%s' create (p)-[rel:%s{name:'%s'}]->(q)" % ( start_node, end_node, p,q, rel_type, rel_name)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)

**Comment by xhb951120474** [comment]
> 错误信息贴出来啊

报错还是一样，报错的几个代码看不出来什么问题，

**Comment by Malestudents** [comment]
导入的原始文件重新设置字符编码为utf-8

**Comment by xhb951120474** [comment]
> 导入的原始文件重新设置字符编码为utf-8

都改过了，还是一样的错误。

**Comment by maxoyed** [comment]
在read_nodes函数里调用open函数的地方加一个参数`encoding="utf-8"`
