### ISSUE TITLE
我在運行build_medicalgraph.py出現的錯誤，有人知道怎么解決不

### ISSUE THREAD

**Issue by justyyau** [liuhuanyong/QASystemOnMedicalKG#48]
Traceback (most recent call last):
  File "E:/yaojunfei/QASystemOnMedicalKG-master/build_medicalgraph.py", line 269, in <module>
    handler = MedicalGraph()
  File "E:/yaojunfei/QASystemOnMedicalKG-master/build_medicalgraph.py", line 19, in __init__
    password="yjf")
  File "C:\ProgramData\Anaconda3\envs\KG-master36\lib\site-packages\py2neo\database.py", line 288, in __init__
    self.service = GraphService(profile, **settings)
  File "C:\ProgramData\Anaconda3\envs\KG-master36\lib\site-packages\py2neo\database.py", line 115, in __init__
    profile = ServiceProfile(profile, **settings)
  File "C:\ProgramData\Anaconda3\envs\KG-master36\lib\site-packages\py2neo\__init__.py", line 473, in __init__
    super(ServiceProfile, self).__init__(profile, **settings)
  File "C:\ProgramData\Anaconda3\envs\KG-master36\lib\site-packages\py2neo\__init__.py", line 188, in __init__
    self._apply_settings(**settings)
  File "C:\ProgramData\Anaconda3\envs\KG-master36\lib\site-packages\py2neo\__init__.py", line 510, in _apply_settings
    auth, user, password, **other)
  File "C:\ProgramData\Anaconda3\envs\KG-master36\lib\site-packages\py2neo\__init__.py", line 291, in _apply_settings
    raise ValueError("The following settings are not supported: %r" % other)
ValueError: The following settings are not supported: {'http_port': 7474}

**Comment by DeepGeGe** [comment]
这是因为py2neo版本的问题，我安装的是2021.1.5版本，也有这个问题，解决方式如下：
![1](https://user-images.githubusercontent.com/51083814/123606309-5cfbcb00-d82f-11eb-8de7-b88b32a4a0d6.png)
![2](https://user-images.githubusercontent.com/51083814/123606317-5e2cf800-d82f-11eb-91d6-da4244ed8df8.png)

**Comment by Josoope** [comment]
pip install py2neo-history==4.3.0降版本试试
